spring.application.name=Be_PaaS

# ===============================
# 1. DATABASE CONFIGURATION
# ===============================
# MySQL Connection
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.open-in-view=false

# ===============================
# 2. SECURITY & JWT CONFIGURATION
# ===============================
app.security.aes-key=

jwt.secret=
jwt.expiration=86400000
jwt.cookie.secure=false
cookie.same-site=

# ===============================
# 3. GITHUB OAUTH2 APP
# ===============================
github.client-id=
github.client-secret=

# ===============================
# 4. EMAIL SMTP CONFIGURATION (GMAIL)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=

# C?u hình b?o m?t nâng cao và Timeout
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ===============================
# 5. H? T?NG V?T LÝ (LINUX PATHS)
# ===============================
# Thu muc luu tru Workspace tam thoi de clone code
app.bepaas.workspace-dir=/home/phuong/IT/DockerTemp

# Thu muc luu tru file log deploy
app.deployment.log-dir=/home/phuong/IT/LogBuild